### ISSUE TITLE
`impl Abomonation for u/i128`

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/abomonation#11] opened 2018-10-05 18:58 UTC
128-bit integers are not abomonable at the moment. Is there a reason not to support this?

**Comment by frankmcsherry** [comment] 2018-10-06 08:51
No reason, except they stabilized relatively recently (and I've never used one). We should be able to just add it to the list of implemented things. Any others come to mind?

**Comment by frankmcsherry** [comment] 2018-10-06 08:54
Actually, there could be an issue if either of these tickle alignment issues. They possibly end up in SIMD registers, and misaligned loads/stores could be actual panics there rather than just perf overhead like it is for other types. I'll implement them and study, and PR if it seems they work.

**Comment by frankmcsherry** [comment] 2018-10-06 10:52
Well, I just tried and .. nothing crashed. The test that serializes, but with a one character string serialized before the `u128`, ran and confirmed that the decoded result `==` the original. Um. Any thoughts on whether that is sufficient? :D

**Comment by ryzhyk** [comment] 2018-10-08 16:02
No idea, tbh. I know that 128-bit integers can be implemented in different ways on different platforms, so I'm not sure what a complete test matrix should look like. But shouldn't it be the compiler's job to make sure that data is properly aligned (perhaps by making an extra copy) before using it in SIMD instructions?

**Comment by frankmcsherry** [comment] 2018-10-12 10:12
Apropos abomonation support, timely just landed a `bincode` feature flag that should allow you to use any types that implement `Serialize+for<'a>Deserialize<'a>`, rather than requiring `Abomonation`. At the moment this includes e.g. `HashMap`, probably `BTree`, maybe some other things. Unfortunately, you still cannot use `f64` types in differential, because they do not implement `Ord`.

**Comment by benesch** [comment] 2019-06-06 20:51
@frankmcsherry I do believe this can be closed now?

**Comment by frankmcsherry** [comment] 2019-07-11 13:08
Yup, it should be good to go (tests recently added, but no surprises there).

**Closed by frankmcsherry** 2019-07-11 13:08 UTC
